// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxJC-t4YCHMsSrmSl1DEu2AKSY5h8qhb8',
    appId: '1:33131971544:web:10f966051e0d8dcaa4e8ad',
    messagingSenderId: '33131971544',
    projectId: 'nursery-a0ebc',
    authDomain: 'nursery-a0ebc.firebaseapp.com',
    storageBucket: 'nursery-a0ebc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBU74NNKJE0S-Lj6VQ_49fp7S5En7mov0',
    appId: '1:33131971544:android:8ec0bb441ae3e88ea4e8ad',
    messagingSenderId: '33131971544',
    projectId: 'nursery-a0ebc',
    storageBucket: 'nursery-a0ebc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPC8JLwGPx-EfwCSo2pd5C8ZDA78Gh4aE',
    appId: '1:33131971544:ios:9a44b227ffe4038da4e8ad',
    messagingSenderId: '33131971544',
    projectId: 'nursery-a0ebc',
    storageBucket: 'nursery-a0ebc.firebasestorage.app',
    iosBundleId: 'com.example.nursery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPC8JLwGPx-EfwCSo2pd5C8ZDA78Gh4aE',
    appId: '1:33131971544:ios:9a44b227ffe4038da4e8ad',
    messagingSenderId: '33131971544',
    projectId: 'nursery-a0ebc',
    storageBucket: 'nursery-a0ebc.firebasestorage.app',
    iosBundleId: 'com.example.nursery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxJC-t4YCHMsSrmSl1DEu2AKSY5h8qhb8',
    appId: '1:33131971544:web:a5e9f487aaf90dc3a4e8ad',
    messagingSenderId: '33131971544',
    projectId: 'nursery-a0ebc',
    authDomain: 'nursery-a0ebc.firebaseapp.com',
    storageBucket: 'nursery-a0ebc.firebasestorage.app',
  );
}
